// Generated by CodiumAI

describe('useDollarRate', () => {

});

    // Tests that the dollar rate is fetched successfully from the API
    it('should set dollarRate state to a number when API call is successful', async () => {
        const mockResponse = {
            data: {
                USDBRL: {
                    bid: '5.25'
                }
            }
        };
        jest.spyOn(axios, 'get').mockResolvedValueOnce(mockResponse);
        const { result, waitForNextUpdate } = renderHook(() => useDollarRate());
        expect(result.current).toBeNull();
        await waitForNextUpdate();
        expect(result.current).toBe(5.25);
    });

