// Generated by CodiumAI

describe('CartProvider', () => {

});

    // Tests that a product can be added to an empty cart
    it('should add a product to an empty cart', () => {
        const product = { id: 1, name: 'Test Product', price: 10 };
        const wrapper = ({ children }) => (
            <CartProvider>{children}</CartProvider>
        );
        const { result } = renderHook(() => useCart(), { wrapper });

        act(() => {
            result.current.addItemToCart(product);
        });

        expect(result.current.cartItems).toEqual([
            { ...product, quantity: 1 }
        ]);
    });

